export const ADD_MESSAGE = 'App/ADD_MESSAGE'
export const ADD_HISTORY = 'App/ADD_HISTORY'
export const ADD_USER = 'App/ADD_USER'
export const REMOVE_USER = 'App/REMOVE_USER'
export const SET_PROFILE = 'App/SET_PROFILE'
export const SET_YOTI_USER = 'App/SET_YOTI_USER'
export const SET_ROOM = 'App/SET_ROOM'
